import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, lstatSync, realpathSync, unlinkSync, renameSync, writeFileSync, existsSync, rmSync } from "node:fs";
import { isAbsolute, join, relative, resolve, sep } from "node:path";
import { loadCanonicalSkills } from "./catalog.ts";
import type { AgentId, IntegrationMetadata, ProjectionFile, ProjectionPlan } from "./types.ts";

const capabilities = ["context", "skills", "workflows", "tools", "verification", "status", "diagnostics", "lifecycle"];

export function metadata(agent: AgentId, projectRoot: string): IntegrationMetadata {
  return {
    id: `paved.integration.${agent}`,
    version: "1.0.0",
    target: agent,
    capabilities,
    root: agent === "codex" ? join(projectRoot, ".agents", "skills") : projectRoot,
  };
}

function header(integration: IntegrationMetadata): string {
  return `<!-- Generated by Paved ${integration.id}@${integration.version}; edit the canonical skill in Paved Core instead. -->\n`;
}

function skillContent(integration: IntegrationMetadata, skill: ReturnType<typeof loadCanonicalSkills>[number]): string {
  const frontmatter = /^---\s*\n[\s\S]*?\n---\s*\n/.exec(skill.body);
  if (frontmatter === null) throw new Error(`Canonical skill ${skill.id} is missing frontmatter.`);
  return `${frontmatter[0]}${header(integration)}${skill.body.slice(frontmatter[0].length)}\n\n## Paved integration\n\nUse the project-local Paved contract as the source of truth. Discover state with \`paved status --json\`, load only relevant \`.paved/project/\` context, and invoke verification with \`paved verify --json\`. Do not edit generated integration files or bypass Paved lifecycle and ownership checks.\n`;
}

export function planProjection(agent: AgentId, projectRoot: string, coreRoot: string): ProjectionPlan {
  const integration = metadata(agent, projectRoot);
  const skills = loadCanonicalSkills(coreRoot);
  const files: ProjectionFile[] = skills.map((skill) => ({
    relativePath: agent === "codex"
      ? join(skill.name, "SKILL.md")
      : join("skills", skill.name, "SKILL.md"),
    content: skillContent(integration, skill),
  }));
  if (agent === "claude-code") {
    files.unshift({
      relativePath: join(".claude-plugin", "plugin.json"),
      content: `${JSON.stringify({
        name: "paved",
        version: integration.version,
        description: `Paved agent skills. Generated by Paved integration ${integration.id}.`,
        skills: "./skills",
      }, null, 2)}\n`,
    });
  }
  return { integration, files, diagnostics: [] };
}

function atomicWrite(path: string, content: string): void {
  const temporaryPath = `${path}.paved-tmp`;
  try {
    writeFileSync(temporaryPath, content, { flag: "wx" });
    renameSync(temporaryPath, path);
  } catch (error) {
    if (existsSync(temporaryPath)) rmSync(temporaryPath, { force: true });
    throw error;
  }
}

function safePath(integration: IntegrationMetadata, relativePath: string): string {
  const projectRoot = integration.target === "codex"
    ? resolve(integration.root, "..", "..")
    : integration.root;
  const resolvedRoot = realpathSync(projectRoot);
  const consumerRelativePath = integration.target === "codex"
    ? join(".agents", "skills", relativePath)
    : relativePath;
  const candidate = resolve(resolvedRoot, consumerRelativePath);
  const pathFromRoot = relative(resolvedRoot, candidate);
  if (pathFromRoot === ".." || pathFromRoot.startsWith(`..${sep}`) || isAbsolute(pathFromRoot)) {
    throw new Error(`Integration path escapes its root: ${relativePath}`);
  }

  let current = resolvedRoot;
  for (const component of pathFromRoot.split(sep).filter(Boolean)) {
    current = join(current, component);
    try {
      if (lstatSync(current).isSymbolicLink()) {
        throw new Error(`Refusing to traverse symbolic link in integration path: ${current}`);
      }
    } catch (error) {
      if (!(error instanceof Error && "code" in error && error.code === "ENOENT")) throw error;
    }
  }

  return candidate;
}

function generatedByPaved(path: string): boolean {
  try {
    const content = readFileSync(path, "utf8");
    if (content.startsWith("<!-- Generated by Paved ")) return true;
    if (/^---\s*\n[\s\S]*?\n---\s*\n<!-- Generated by Paved /.test(content)) return true;
    if (path.endsWith("plugin.json")) {
      const descriptor = JSON.parse(content) as {
        description?: unknown;
        _paved?: { generated?: unknown };
      };
      return descriptor._paved?.generated === true
        || (typeof descriptor.description === "string"
          && descriptor.description.startsWith("Paved agent skills. Generated by Paved integration "));
    }
    return false;
  }
  catch { return false; }
}

export function applyProjection(plan: ProjectionPlan): { changed: number; unchanged: number } {
  let changed = 0;
  let unchanged = 0;
  for (const file of plan.files) {
    const path = safePath(plan.integration, file.relativePath);
    mkdirSync(resolve(path, ".."), { recursive: true });
    safePath(plan.integration, file.relativePath);
    try {
      if (lstatSync(path).isSymbolicLink()) throw new Error(`Refusing to write through symlink: ${path}`);
      if (readFileSync(path, "utf8") === file.content) { unchanged += 1; continue; }
      if (!generatedByPaved(path)) throw new Error(`Refusing to overwrite user-owned integration file: ${path}`);
    } catch (error) {
      if (!(error instanceof Error && "code" in error && error.code === "ENOENT")) throw error;
    }
    atomicWrite(path, file.content);
    changed += 1;
  }
  return { changed, unchanged };
}

export function removeProjection(plan: ProjectionPlan): number {
  let removed = 0;
  for (const file of plan.files) {
    const path = safePath(plan.integration, file.relativePath);
    if (generatedByPaved(path)) {
      safePath(plan.integration, file.relativePath);
      unlinkSync(path);
      removed += 1;
    }
  }
  if (plan.integration.target === "claude-code") {
    const plugin = safePath(plan.integration, join(".claude-plugin", "plugin.json"));
    if (generatedByPaved(plugin)) {
      safePath(plan.integration, join(".claude-plugin", "plugin.json"));
      unlinkSync(plugin);
    }
  }
  return removed;
}

export function digest(content: string): string {
  return createHash("sha256").update(content).digest("hex");
}

export function projectionPaths(plan: ProjectionPlan): string[] {
  return plan.files.map((file) => safePath(plan.integration, file.relativePath));
}
